frontend/models/Employee.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "employee".
 *
 * @property integer $id
 * @property string $name
 * @property integer $age
 * @property integer $place
 * @property integer $status
 *
 * @property Country $place0
 * @property Works[] $works
 */
class Employee extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'employee';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'age', 'place'], 'required'],
            [['age', 'place', 'status'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['place'], 'exist', 'skipOnError' => true, 'targetClass' => Country::className(), 'targetAttribute' => ['place' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'age' => 'Age',
            'place' => 'Place',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlace0()
    {
        return $this->hasOne(Country::className(), ['id' => 'place']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorks()
    {
        return $this->hasMany(Works::className(), ['empId' => 'id']);
    }
}

frontend/controllers/EmployeeController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Employee;
use app\models\EmployeeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EmployeeController implements the CRUD actions for Employee model.
 */
class EmployeeController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Employee models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EmployeeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Employee model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionChange($id)
    {
        $emp = $this->findModel($id);
         if (isset($_POST['hasEditable'])) {
        // use Yii's response format to encode output as JSON
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $post['Employee']  = $_POST['Employee'][$_POST['editableIndex']];
        if($emp->load($post)){
        $emp->save();
        return ['output'=>'', 'message'=>''];
        }
         }
    }

    /**
     * Creates a new Employee model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Employee();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Employee model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Employee model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Employee model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Employee the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employee::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/employee/_expand-row-details.php
<div class="table">
Name : <?=$model->name?><br />
Age : <?=$model->age?><br />
Place : <?=$model->place?><br />
</div>

frontend/views/employee/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employee-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'age')->textInput() ?>

    <? # $form->field($model, 'place')->textInput(['maxlength' => true]) ?>
<?
$data = \yii\helpers\ArrayHelper::map(\app\models\Country::find()->asArray()->all(), 'id', 'name');
echo $form->field($model, 'place')->widget(Select2::classname(), [
    'data' => $data,
]);

?>
    <?= $form->field($model, 'status')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/employee/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EmployeeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employee-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'age') ?>

    <?= $form->field($model, 'place') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/employee/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Employee */

$this->title = 'Create Employee';
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employee-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/employee/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EmployeeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Employees ';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employee-index">

    <h1><?= $this->title ?>- <small>Please mail me your feedback <b><a href="mailto:coder@omsc.in">coder@omsc.in</a></b></small></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <? #Html::a('Create Employee', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?
 
    
    $gridColumns = [
                    [
                        'class'=>'kartik\grid\SerialColumn',
                    ],
                    /*[
                        'class'=>'kartik\grid\RadioColumn',
                        'width'=>'36px',
                        'headerOptions'=>['class'=>'kartik-sheet-style'],
                    ],*/
                    [
                        'class'=>'kartik\grid\ExpandRowColumn',
                        'width'=>'50px',                        
                      //  'group'=>true,
                        'value'=>function ($model, $key, $index, $column) {
                            return GridView::ROW_COLLAPSED;
                        },
                        'detail'=>function ($model, $key, $index, $column) {
                            return Yii::$app->controller->renderPartial('_expand-row-details', ['model'=>$model,'id'=>$key]);
                        },
                        'headerOptions'=>['class'=>'kartik-sheet-style'], 
                        'expandOneOnly'=>true
                    ],
                    
                    [
                        'class'=>'kartik\grid\EditableColumn',
                        'attribute'=>'name',
                        'pageSummary'=>'Total',
                                             
                        'group'=>true,
                       // 'subGroupOf'=>1,
                        'groupHeader'=>function ($model, $key, $index, $widget) { // Closure method
                                return [
                                    'mergeColumns'=>[[2,4]], // columns to merge in summary
                                    'content'=>[             // content to show in each summary cell
                                        2=>'Summary (' . $model->name  . ')',
                                        //4=>GridView::F_AVG,
                                        //5=>GridView::F_SUM,
                                       // 6=>GridView::F_SUM,
                                    ],
                                    'contentFormats'=>[      // content reformatting for each summary cell
                                        4=>['format'=>'number', 'decimals'=>2],
                                        //5=>['format'=>'number', 'decimals'=>0],
                                        //6=>['format'=>'number', 'decimals'=>2],
                                    ],
                                    'contentOptions'=>[      // content html attributes for each summary cell
                                        2=>['style'=>'font-variant:small-caps'],
                                        4=>['style'=>'text-align:right'],
                                        //5=>['style'=>'text-align:right'],
                                        //6=>['style'=>'text-align:right'],
                                    ],
                                    // html attributes for group summary row
                                    'options'=>['class'=>'danger','style'=>'font-weight:bold;']
                                ];
                            },
                        'editableOptions'=>function ($model, $key, $index) {
                        return [
                            'formOptions'=>['action'=>Url::to(['employee/change','id'=>$model->id])],
                            'header'=>'Buy Amount', 
                           //'inputType'=>\kartik\editable\Editable::INPUT_SPIN,
                            
                            'options'=>[
                                'pluginOptions'=>['min'=>0, 'max'=>5000,]
                            ]
                        ];},
                        'vAlign'=>'top',
                        'width'=>'210px',
                        'readonly'=>function($model, $key, $index, $widget) {
                            return (!$model->status); // do not allow editing of inactive records
                        },
                       
                    ],
                     [
            'attribute'=>'place', 
            'width'=>'250px',
            'value'=>function ($model, $key, $index, $widget) { 
                return $model->place0->name;
            },
            'filterType'=>GridView::FILTER_SELECT2,
            'filter'=>\yii\helpers\ArrayHelper::map(\app\models\Country::find()->asArray()->all(), 'id', 'name'), 
            'filterWidgetOptions'=>[
                'pluginOptions'=>['allowClear'=>true],
            ],
            'filterInputOptions'=>['placeholder'=>'Any Country'],
            'group'=>true,  // enable grouping
            'subGroupOf'=>2, // supplier column index is the parent group,
            'groupFooter'=>function ($model, $key, $index, $widget) { // Closure method
                return [
                    'mergeColumns'=>[[3, 4]], // columns to merge in summary
                    'content'=>[              // content to show in each summary cell
                        3=>'Summary (' . $model->place0->name . ')',
                        //4=>GridView::F_AVG,
                        //5=>GridView::F_SUM,
                        //6=>GridView::F_SUM,
                    ],
                    'contentFormats'=>[      // content reformatting for each summary cell
                        4=>['format'=>'number', 'decimals'=>2],
                        5=>['format'=>'number', 'decimals'=>0],
                        6=>['format'=>'number', 'decimals'=>2],
                    ],
                    'contentOptions'=>[      // content html attributes for each summary cell
                        4=>['style'=>'text-align:right'],
                        5=>['style'=>'text-align:right'],
                        6=>['style'=>'text-align:right'],
                    ],
                    // html attributes for group summary row
                    'options'=>['class'=>'success','style'=>'font-weight:bold;']
                ];
            },
        ],
                 
                    [
                        'class'=>'kartik\grid\EditableColumn',
                        'attribute'=>'age', 
                        'readonly'=>function($model, $key, $index, $widget) {
                            return (!$model->status); // do not allow editing of inactive records
                        },
                        'editableOptions'=>function ($model, $key, $index) {
                        return [
                            'formOptions'=>['action'=>Url::to(['employee/change','id'=>$model->id])],
                            'header'=>'Buy Amount', 
                            'inputType'=>\kartik\editable\Editable::INPUT_SPIN,
                            
                            'options'=>[
                                'pluginOptions'=>['min'=>0, 'max'=>5000,]
                            ]
                        ];},
                        'hAlign'=>'right', 
                        'vAlign'=>'middle',
                        'width'=>'7%',
                        'format'=>['decimal', 2],
                        //'pageSummary'=>true
                    ],
                      [
                        'attribute'=>'place',
                        'filter'=>false,
                        'value'=>function ($model, $key, $index, $widget) {
                            return $model->place ;
                        },
                        'width'=>'8%',
                        'vAlign'=>'middle',
                        'format'=>'raw',
                        'noWrap'=>1
                    ],
                    /*
                    [
                        'attribute'=>'status', 
                        'vAlign'=>'middle',
                        'hAlign'=>'right', 
                        'width'=>'7%',
                        'format'=>['decimal', 2],
                        'pageSummary'=>true
                    ],*/
                    
                    
                    ];
                            
                            ?>
    <?= GridView::widget([
    'dataProvider'=> $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumns,
    'responsive'=>true,
    'hover'=>true
]); ?>

</div>

frontend/views/employee/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */

$this->title = 'Update Employee: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="employee-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/employee/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employee-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'age',
            'place',
            'status',
        ],
    ]) ?>

</div>